BlogApp/Controllers/CmsController.cs
using System;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Web.Mvc;
using BlogApp.Models;



namespace BlogApp.Controllers
{
    [KullaniciGiris]
    public class CmsController : Controller
    {
        private readonly BlogDBEntities _context;

        public CmsController()
        {
            _context = new BlogDBEntities();
        }

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult MakaleListesi()
        {
            var liste = _context.Makale.OrderByDescending(x => x.EklenmeTarihi).ToList();
            return View(liste);
        }
        [HttpGet]
        public ActionResult MakaleEkle()
        {
            return View();
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult MakaleEkle(Makale makale)
        {

            makale.EklenmeTarihi = DateTime.Now;
            _context.Makale.Add(makale);
            _context.SaveChanges();

            return RedirectToAction("MakaleListesi");

        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult MakaleGuncelle(Makale makale)
        {
            var guncelle = _context.Makale.Find(makale.MakaleId);
            guncelle.MakaleBaslik = makale.MakaleBaslik;
            guncelle.MakaleBaslikEn = makale.MakaleBaslikEn;
            guncelle.MakaleOzet = makale.MakaleOzet;
            guncelle.MakaleOzetEn = makale.MakaleOzetEn;
            guncelle.MakaleDetay = makale.MakaleDetay;
            guncelle.MakaleDetayEn = makale.MakaleDetayEn;

            _context.Makale.AddOrUpdate(guncelle);

            _context.SaveChanges();
            return RedirectToAction("MakaleListesi");

        }

        public ActionResult MakaleGit(int id)
        {
            var git = _context.Makale.Find(id);
            var makale = new Makale
            {
                MakaleId = git.MakaleId,
                MakaleBaslik = git.MakaleBaslik,
                MakaleBaslikEn = git.MakaleBaslikEn,
                MakaleOzet = git.MakaleOzet,
                MakaleOzetEn = git.MakaleOzetEn,
                MakaleDetay = git.MakaleDetay,
                MakaleDetayEn = git.MakaleDetayEn,

            };
            return View(makale);
        }





        public ActionResult MakaleSil(int id)
        {
            var makale = _context.Makale.Find(id);
            _context.Makale.Remove(makale);

            _context.SaveChanges();
            return RedirectToAction("MakaleListesi");
        }





        public ActionResult YorumListesi()
        {
            return View();
        }



    }
}

BlogApp/Controllers/LanguageController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using BlogApp.Models;

namespace BlogApp.Controllers
{
    public class LanguageController : Controller
    {

        private readonly BlogDBEntities _context;

        public LanguageController()
        {
            _context = new BlogDBEntities();
        }
        // GET: Language
        public ActionResult Index()
        {
            var liste = _context.Makale.OrderByDescending(x => x.EklenmeTarihi).ToList();
            return View(liste);
        }


        public ActionResult LatestArticle()
        {
            var liste = _context.Makale.OrderByDescending(x => x.EklenmeTarihi).Take(5).Take(5).ToList();
            return View(liste);
        }


        public ActionResult ArticleDetail(int id)
        {
            var oku = _context.Makale.Find(id);
            return View(oku);
        }


        [HttpPost]
        public ActionResult ArticleDetail(FormCollection frm)
        {
            Yorum yorum = new Yorum();

            yorum.MakaleId = Convert.ToInt32(frm["MakaleId"].Trim());
            yorum.AdSoyad = frm["adsoyad"].Trim();
            yorum.YorumDetay = frm["yorumdetay"].Trim();
            yorum.YorumTarih = DateTime.Now;

            _context.Yorum.Add(yorum);
            _context.SaveChanges();
            return Redirect("/Language/ArticleDetail/" + yorum.MakaleId);
        }

       

        public ActionResult Commend(int id)
        {
            var makale = _context.Makale.Find(id);
            return View(makale.Yorum.ToList());
        }


    }
}

BlogApp/Views/Language/ArticleDetail.cshtml
@model BlogApp.Models.Makale
@{
    ViewBag.Title = "ArticleDetail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{ Html.RenderPartial("UstMenu");}

<div class="row">

    <!-- Blog Post Content Column -->
    <div class="col-lg-8">


        <!-- Blog Post -->
        <!-- Title -->
        <h1>@Model.MakaleBaslikEn</h1>

        <!-- Author -->


        <p>
            <span class="glyphicon glyphicon-time"></span> Eklenme Tarihi : @Model.EklenmeTarihi
        </p>



        <!-- Post Content -->
        <p class="lead">@Html.Raw(Model.MakaleDetayEn)</p>

        @if (HttpContext.Current.Session["UserInfo"] != null)
        {
            using (Html.BeginForm("ArticleDetail", "Language", FormMethod.Post))
            {
                @*<input type="hidden" name="gelenId" value="@Model.MakaleId">*@
                @Html.HiddenFor(x => x.MakaleId)
                <div class="well">
                    <h4>Commend:</h4>
                    <form role="form">



                        <div class="form-group">
                            <input type="text" name="adsoyad" class="form-control" placeholder="Full Name" />

                        </div>
                        <div class="form-group">
                            <textarea class="form-control" rows="3" name="yorumdetay" placeholder="Commend"></textarea>

                        </div>



                        <button type="submit" class="btn btn-primary">Send</button>
                    </form>
                </div>

            }
        }



        <hr>

        <!-- Posted Comments -->
        @{Html.RenderAction("Yorum", "Home");}

    </div>

    <!-- Blog Sidebar Widgets Column -->
    <div class="col-md-4">


        @{Html.RenderAction("LatestArticle");}

    </div>

</div>

BlogApp/Views/Language/Commend.cshtml
@using BlogApp.Models
@model List<BlogApp.Models.Yorum>



@foreach (var yorum in Model)
{

    <div class="media">
        <a class="pull-left" href="#">

            <img class="media-object" src="~/Content/profile.png" alt="">
        </a>
        <div class="media-body">
            <h4 class="media-heading">
                @yorum.AdSoyad
            </h4>
            @yorum.YorumDetay
        </div>
    </div>
}

BlogApp/Views/Language/Index.cshtml
@model List<BlogApp.Models.Makale>
@{
    ViewBag.Title = "English";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@{ Html.RenderPartial("UstMenu");}
<div class="row">

    <!-- Blog Post Content Column -->
    <div class="col-lg-8">
        @foreach (var makale in Model)
        {

        <!-- Blog Post -->
        <!-- Title -->
            <h1><a href="~/Language/ArticleDetail/@makale.MakaleId">@makale.MakaleBaslikEn</a></h1>

        <!-- Author -->


            <p>
                <span class="glyphicon glyphicon-time"></span> Date Added : @makale.EklenmeTarihi
            </p>



            <!-- Post Content -->
            <p class="lead">@Html.Raw(makale.MakaleOzetEn)</p>

            <hr>

        }


    </div>

    <!-- Blog Sidebar Widgets Column -->
    <div class="col-md-4">

        @{ Html.RenderAction("LatestArticle");}



    </div>

</div>

BlogApp/Views/Language/LatestArticle.cshtml
@model List<BlogApp.Models.Makale>
<div class="well">
    <h4>Latest Article</h4>
    <div class="row">
        <div class="col-lg-6">
            <ul class="list-unstyled">
                @foreach (var baslik in Model)
                {
                    <li>
                        <a href="~/Language/ArticleDetail/@baslik.MakaleId">@baslik.MakaleBaslikEn</a>
                    </li>
                }
            </ul>
        </div>

    </div>
    <!-- /.row -->
</div>

BlogApp/Views/Language/UstMenu.cshtml
<!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="@Url.Action("Index","Language")">MyBlog</a>

            @if (HttpContext.Current.Session["UserInfo"] != null)
            {
                var kullanici = HttpContext.Current.Session["UserInfo"] as BlogApp.Models.Kullanici;
                if (kullanici.KullaniciId == 2)
                {
                    <a class="navbar-brand" href="@Url.Action("Index","Cms")">Management Panel</a>
                }
                <a class="navbar-brand" href="@Url.Action("LogOff","Login")">Log Off</a>
                <a class="navbar-brand" href="@Url.Action("Index","Home")">TR</a>
                <a class="navbar-brand" href="@Url.Action("Index","Language")">EN</a>

            }
            else
            {
                <a class="navbar-brand" href="@Url.Action("Index","Login")">Sign in</a>
                <a class="navbar-brand" href="@Url.Action("KayitOl","Login")">Sign up</a>
                <a class="navbar-brand" href="@Url.Action("Index","Home")">TR</a>
                <a class="navbar-brand" href="@Url.Action("Index","Language")">EN</a>
            }

        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>